### ISSUE TITLE
Mocha reporting global leaks when using animation-frame

### ISSUE THREAD

**Issue by qinfchen** [kof/animation-frame#16]
Error: global leak detected: i

**Comment by kof** [comment]
you need to give me more than that.

also which version

**Comment by qinfchen** [comment]
i am using 0.1.7. Looks like it may not be related to aniamtion-frame. Let me double check

**Comment by kof** [comment]
also try the latest version from master

**Comment by qinfchen** [comment]
I am still seeing the error. Here is the code. 
```typescript
var animationFrame = new AnimationFrame();
...
function frame() {
    if (tick()) {
        return;
    }
    animationFrame.request(frame);
}
animationFrame.request(frame);
```

**Comment by kof** [comment]
by still you mean using 0.2.0 ?

**Comment by kof** [comment]
the only thing you don is to run the code above, nothing else?

**Comment by qinfchen** [comment]
Yes, i am still seeing the error using master. I also run `tick()` directly without the code above. Without the code above, the error goes away.

**Comment by kof** [comment]
how do you run this code, it depends also on window ...

**Comment by kof** [comment]
OK I have pushed  a new version with universal global detection. And I run this code
`mocha test.js`

    // test.js
    var AnimationFrame = require('./index')

    var animationFrame = new AnimationFrame();

    function frame() {
        animationFrame.request(frame);
    }
    animationFrame.request(frame);


don't see any errors.

**Comment by kof** [comment]
it has something to do with your setup.

**Comment by qinfchen** [comment]
hmm... can you elaborate on the "on windows..."?

**Comment by qinfchen** [comment]
Yep, this was related to the library that was calling it. Thanks for the hlep
