### ISSUE TITLE
IE8 & 9 fail

### ISSUE THREAD

**Issue by RadekDvorak** [kof/animation-frame#17]
IE8 fails with current master (3820dbc290f5b0775296acbf47625242f0dcba39):

    Webpage error details

    User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
    Timestamp: Sat, 17 Jan 2015 09:39:43 UTC

    Message: Object doesn't support this property or method
    Line: 111
    Char: 9
    Code: 0
    URI: http://example.com/AnimationFrame.js

IE9 is mor specific:

    SCRIPT438: Object doesn't support property or method 'setTimeout' 
    AnimationFrame.js, line 111 character 9

**Comment by kof** [comment]
seems like https://github.com/kof/animation-frame/blob/master/lib/global.js implementation of global isn't working properly ... strange ... need to verify it, usually @kangax doesn't lie :)

**Comment by kof** [comment]
fixed and published
