### ISSUE TITLE
Create bundled version

### ISSUE THREAD

**Issue by grifotv** [kof/animation-frame#22]
Like in version [0.1.7](https://github.com/kof/animation-frame/blob/0.1.7/AnimationFrame.js), it would be great if version 0.2.4 would also have a bundled version, a single JS file that does not require additional files.

Would be good to avoid this https://github.com/kof/animation-frame/blob/0.2.4/AnimationFrame.js#L10 or at least create an additional bundled file.

**Comment by kof** [comment]
I am not sure what you are talking about, its bundled with browserify, this file doesn't require anything else to work ...

**Comment by grifotv** [comment]
The issue I'm having is when configuring an app with browserify-shim (http://stackoverflow.com/a/25585778) and using your library as a vendor. Somehow with version 0.1.7 everything was working smoothly, but now with version 0.2.4 I get the error message:

![screen shot 2015-03-05 at 09 13 00](https://cloud.githubusercontent.com/assets/435351/6502082/ed8d069a-c317-11e4-9bee-6dab3e20a20b.png)

I also don't have any issues with any other vendors (eg: backbone marionette, handlebars, lodash, jquery, js-signals, fastclick, pixi etc).

My project's package.json looks like this:

```
{
  "name": "xxx",
  "description": "",
  "version": "0.0.1",
  "private": true,
  "repository": {
    "type": "git",
    "url": "xxx"
  },
  "dependencies": {},
  "devDependencies": {
    "browserify": "^8.1.3",
    "browserify-shim": "^3.8.2",
    "gulp": "^3.8.11"
  },
  "browser": {
    "underscore": "./dist/assets/vendor/lodash/lodash.js",
    "jquery": "./dist/assets/vendor/jquery/dist/jquery.js",
    "handlebars": "./dist/assets/vendor/handlebars/handlebars.js",
    "backbone": "./dist/assets/vendor/backbone/backbone.js",
    "animation-frame": "./dist/assets/vendor/animation-frame/AnimationFrame.js"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "underscore": "_",
    "jquery": "$",
    "handlebars": "Handlebars",
    "backbone": {
      "exports": "Backbone",
      "depends": [
        "underscore",
        "jquery"
      ]
    },
    "animation-frame": "AnimationFrame"
  }
}
```

I'm not sure what would be the ideal solution, but I thought it would be good to let you know. For now, I'll carry on my project with version 0.1.7.

**Comment by kof** [comment]
remove animation-frame from the browser hash, it is already cjs, doesn't require anything.

**Comment by grifotv** [comment]
Sorry I'm not sure I'm following, how do I do that?

**Comment by kof** [comment]
try to remove this line

```
    "animation-frame": "./dist/assets/vendor/animation-frame/AnimationFrame.js"

```

**Comment by grifotv** [comment]
I tried a couple of different approaches:

### 1 - Point to `AnimationFrame.js` with browserify-shim:
package.json:
`"animation-frame": "./dist/assets/vendor/animation-frame/AnimationFrame.js",`

frontend js app:
`var AnimationFrame = require('animation-frame');`

chrome console error:
`Uncaught Error: Cannot find module './lib/animation-frame'`

### 2 - Point to `lib/animation-frame.js` with browserify-shim:

package.json:
`"animation-frame": "./dist/assets/vendor/animation-frame/lib/animation-frame.js",`

frontend js app:
`var AnimationFrame = require('animation-frame');`

chrome console error:
`Uncaught Error: Cannot find module './native'`

### 3 - Point to `AnimationFrame.js` without browserify-shim:

frontend js app:
`var AnimationFrame = require('../../../../dist/assets/vendor/animation-frame/AnimationFrame');`

gulp compile error:
`Error: Cannot find module './native' from '/Users/username/repositories/test/build/dist/assets/vendor/animation-frame'`

### 4 - Point to `lib/animation-frame.js` without browserify-shim:

frontend js app:
`var AnimationFrame = require('../../../../dist/assets/vendor/animation-frame/lib/animation-frame');`

**It works fine!** :+1: 

------------

Anyways, it's a bit of a shame it doesn't work with browserify-shim.

**Comment by kof** [comment]
what about no browserify-shim and require('animation-frame')

**Comment by grifotv** [comment]
that option won't even compile.

gulp compile error:
`Error: Cannot find module 'animation-frame' from '/Users/username/repositories/test/build/src/js/app/views'`

**Comment by kof** [comment]
I don't know exactly what your gulp does, but browserify works perfectly with this https://github.com/kof/animation-frame/blob/master/Makefile

**Comment by grifotv** [comment]
I think I'll try next to split vendors and app code intro two different JS files ;)
